from __future__ import annotations

import asyncio
import concurrent.futures
import json
import logging
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Coroutine, Dict, TypeVar

from services.executor.git_ops import GitOperations
from services.executor.github_delivery import GitHubDeliveryService
from services.executor.llm_codegen import LLMCodeSynthesizer, SynthesizedCode

logger = logging.getLogger(__name__)

_PYTHON_BIN = sys.executable or "python3"

T = TypeVar("T")


def run_coroutine_in_thread(coro: Coroutine[Any, Any, T], *, timeout: int = 120) -> T:
    """Run an async coroutine from sync code, handling nested event loops."""
    try:
        loop = asyncio.get_event_loop()
        if loop.is_running():
            with concurrent.futures.ThreadPoolExecutor() as pool:
                return pool.submit(asyncio.run, coro).result(timeout=timeout)
        else:
            return asyncio.run(coro)
    except RuntimeError:
        return asyncio.run(coro)


class StageExecutionError(Exception):
    pass


class StageDispatcher:
    def __init__(
        self,
        workspace_root: Path,
        git_ops: GitOperations,
        delivery: GitHubDeliveryService,
        llm_synthesizer: LLMCodeSynthesizer | None = None,
    ):
        self.workspace_root = workspace_root
        self.git_ops = git_ops
        self.delivery = delivery
        self.llm_synthesizer = llm_synthesizer or LLMCodeSynthesizer()
        self._strict = os.getenv("SWARMFORGE_STRICT_STAGE_FAILURES", "false").lower() == "true"
        self._handlers: Dict[str, Any] = {
            "intent-analysis": self._handle_intent,
            "solution-plan": self._handle_plan,
            "code-generation": self._handle_codegen,
            "code-review": self._handle_code_review,
            "test-verification": self._handle_test_verification,
            "security-check": self._handle_security_check,
            "e2e-verification": self._handle_e2e,
            "ui-accessibility-gate": self._handle_ui_a11y,
            "documentation": self._handle_documentation,
            "post-deploy-slo-gate": self._handle_slo_gate,
            "release-gate": self._handle_release_gate,
        }

    def task_run_dir(self, task_id: str) -> Path:
        stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        path = self.workspace_root / ".swarmforge" / "runs" / task_id / stamp
        path.mkdir(parents=True, exist_ok=True)
        return path

    def execute_stage(self, task_id: str, stage: str, context: dict[str, Any]) -> Dict[str, Any]:
        run_dir = self.task_run_dir(task_id)
        result: Dict[str, Any] = {"run_dir": str(run_dir), "stage": stage}
        handler = self._handlers.get(stage)
        if handler:
            handler(run_dir, task_id, context, result)
        else:
            result["artifact"] = None
        return result

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------

    def _raise_if_strict(self, result: Dict[str, Any]) -> None:
        if self._strict and result.get("warning"):
            raise StageExecutionError(result["warning"])

    def _get_delivery_workspace(self, context: dict[str, Any]) -> Path | None:
        """Get the delivery workspace from prior codegen stage."""
        ws = context.get("_delivery_workspace")
        if ws:
            path = Path(ws)
            if path.is_dir():
                return path
        return None

    def _collect_delivery_code(self, context: dict[str, Any]) -> str:
        """Collect generated code from delivery workspace for LLM analysis.

        Only includes files that were generated by the LLM synthesizer,
        not pre-existing code in the cloned repo.
        """
        workspace = self._get_delivery_workspace(context)
        if not workspace:
            return "No delivery workspace available"

        # Get the list of generated file paths from prior codegen results
        prior = context.get("_prior_results", {})
        codegen = prior.get("code-generation", {})
        generated_paths: list[str] = codegen.get("_generated_file_paths", [])

        if generated_paths:
            # Only collect the specific files we generated
            result: list[str] = []
            for rel_path in generated_paths:
                full_path = workspace / rel_path
                if full_path.is_file():
                    try:
                        content = full_path.read_text(encoding="utf-8")
                        result.append(f"=== {rel_path} ===\n{content}\n\n")
                    except (UnicodeDecodeError, PermissionError):
                        continue
            return "".join(result) if result else "No generated files found"

        # Fallback: collect all code files
        from services.executor.llm_stages import collect_generated_files
        return collect_generated_files(workspace)

    def _run_command_gate(
        self,
        *,
        command: list[str],
        run_dir: Path,
        artifact_name: str,
        failure_label: str,
        result: Dict[str, Any],
        cwd: Path | None = None,
    ) -> Dict[str, Any]:
        """Generic handler for command-based quality gates."""
        cmd_result = self.git_ops.run_command(command, cwd=cwd)
        (run_dir / artifact_name).write_text(json.dumps(cmd_result, indent=2), encoding="utf-8")
        result["artifact"] = artifact_name
        result["command"] = cmd_result["command"]
        if cmd_result["returncode"] != 0:
            result["warning"] = (
                f"{failure_label} (exit={cmd_result['returncode']}): "
                f"{cmd_result['stderr_tail'] or cmd_result['stdout_tail']}"
            )
            self._raise_if_strict(result)
        return cmd_result

    # ------------------------------------------------------------------
    # Stage handlers
    # ------------------------------------------------------------------

    def _handle_intent(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        brief = {
            "task_id": task_id,
            "summary": context.get("summary", ""),
            "labels": context.get("labels", []),
            "source": context.get("source"),
        }
        (run_dir / "intent.json").write_text(json.dumps(brief, indent=2), encoding="utf-8")
        result["artifact"] = "intent.json"

    def _handle_plan(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        summary = context.get("summary", "")
        labels = context.get("labels", [])

        llm_enabled = os.getenv("SWARMFORGE_LLM_CODEGEN_ENABLED", "true").lower() == "true"
        if llm_enabled:
            plan_result = self._run_llm_plan(task_id, context)
            if plan_result:
                (run_dir / "PLAN.md").write_text(plan_result, encoding="utf-8")
                result["artifact"] = "PLAN.md"
                result["llm_generated"] = True
                return

        plan_md = (
            f"# Plan for {task_id}\n\n"
            f"- Summary: {summary}\n"
            f"- Labels: {', '.join(labels) if labels else 'none'}\n"
            "- Steps:\n"
            "  1. Understand requirements\n"
            "  2. Implement minimal safe change\n"
            "  3. Verify tests and logs\n"
        )
        (run_dir / "PLAN.md").write_text(plan_md, encoding="utf-8")
        result["artifact"] = "PLAN.md"

    def _run_llm_plan(self, task_id: str, context: dict[str, Any]) -> str | None:
        try:
            from langchain_core.messages import HumanMessage, SystemMessage
        except Exception:
            HumanMessage = None  # type: ignore[assignment]
            SystemMessage = None  # type: ignore[assignment]

        client = self.llm_synthesizer._get_llm_client()
        summary = context.get("summary", "")
        labels = context.get("labels", [])

        system_content = (
            "You are SwarmForge, an autonomous planning agent. "
            "Given a Jira ticket, produce a concise implementation plan in Markdown. "
            "Include: goal, approach, files to modify/create, risks, and verification steps."
        )
        user_content = (
            f"Create an implementation plan for:\n"
            f"- Issue: {task_id}\n"
            f"- Summary: {summary}\n"
            f"- Labels: {', '.join(str(l) for l in labels) or 'none'}\n"
        )

        if SystemMessage is not None and HumanMessage is not None:
            messages = [SystemMessage(content=system_content), HumanMessage(content=user_content)]
        else:
            messages = [
                {"role": "system", "content": system_content},
                {"role": "user", "content": user_content},
            ]

        try:
            response = run_coroutine_in_thread(client.chat(messages), timeout=60)
            return response.content if hasattr(response, "content") else str(response)
        except Exception as exc:
            logger.warning("LLM plan generation failed, falling back to template: %s", exc)
            return None

    def _handle_codegen(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        llm_enabled = os.getenv("SWARMFORGE_LLM_CODEGEN_ENABLED", "true").lower() == "true"
        synthesized: SynthesizedCode | None = None

        if llm_enabled:
            research_output = self._load_research_context(run_dir)
            synthesized = self._run_llm_codegen(context, research_output)

        trace_lines = [
            "# Code Generation Trace\n",
            f"- task: {task_id}",
            f"- time: {datetime.now(UTC).isoformat()}",
            f"- mode: {'llm-synthesized' if synthesized and not synthesized.error else 'autonomous-executor'}",
        ]
        if synthesized and not synthesized.error:
            trace_lines.append(f"- files_generated: {len(synthesized.files)}")
            trace_lines.append(f"- summary: {synthesized.summary}")
            trace_lines.append(f"- reasoning: {synthesized.reasoning}")
            generated_paths = [f["path"] for f in synthesized.files if f.get("path")]
            result["llm_synthesis"] = {
                "files_count": len(synthesized.files),
                "summary": synthesized.summary,
            }
            result["_generated_file_paths"] = generated_paths
        elif synthesized and synthesized.error:
            trace_lines.append(f"- llm_error: {synthesized.error}")
            result["llm_error"] = synthesized.error

        (run_dir / "CODEGEN.md").write_text("\n".join(trace_lines) + "\n", encoding="utf-8")
        result["artifact"] = "CODEGEN.md"

        # Run code sandbox validation on generated files before delivery.
        if synthesized and synthesized.files and not synthesized.error:
            sandbox_result = self._validate_generated_code(run_dir, synthesized)
            result["sandbox_validation"] = sandbox_result
            if not sandbox_result.get("passed", True):
                result["warning"] = f"Code sandbox validation failed: {sandbox_result.get('errors', [])}"
                self._raise_if_strict(result)

        result["delivery"] = self.delivery.create_pr_for_jira_issue(
            run_dir, context, synthesized_code=synthesized,
        )

    def _validate_generated_code(self, run_dir: Path, synthesized: SynthesizedCode) -> dict[str, Any]:
        """Write generated files to temp dir and run sandbox validation."""
        sandbox_dir = run_dir / "_sandbox"
        sandbox_dir.mkdir(parents=True, exist_ok=True)
        for file_entry in synthesized.files:
            file_path = sandbox_dir / file_entry["path"]
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(file_entry["content"], encoding="utf-8")

        from services.executor.code_sandbox import CodeSandbox
        sandbox = CodeSandbox(sandbox_dir)
        return sandbox.validate()

    def _load_research_context(self, run_dir: Path) -> str:
        """Load research output from a prior intent-analysis or solution-plan stage."""
        for candidate in [run_dir.parent, run_dir]:
            for name in ("PLAN.md", "intent.json"):
                path = candidate / name
                if path.exists():
                    try:
                        return path.read_text(encoding="utf-8")[:4000]
                    except Exception:
                        continue
        return ""

    def _run_llm_codegen(
        self, context: dict[str, Any], research_output: str
    ) -> SynthesizedCode | None:
        try:
            return run_coroutine_in_thread(
                self.llm_synthesizer.synthesize(context, research_output),
                timeout=120,
            )
        except Exception as exc:
            logger.warning("LLM code synthesis failed: %s", exc)
            return SynthesizedCode(error=str(exc))

    def _handle_code_review(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """LLM-powered code review of generated code."""
        files_content = self._collect_delivery_code(context)
        summary = context.get("summary", "")

        if files_content == "No delivery workspace available":
            # Fallback: run SwarmForge's own tests as a proxy
            review_result = self.git_ops.run_first_available(
                [
                    [_PYTHON_BIN, "-m", "pytest", "-q", "tests/test_quality_gate.py", "tests/test_orchestrator.py"],
                    ["git", "status", "--short"],
                ]
            )
            (run_dir / "REVIEW.json").write_text(json.dumps(review_result, indent=2), encoding="utf-8")
            result["artifact"] = "REVIEW.json"
            result["review_mode"] = "fallback_self_test"
            return

        from services.executor.llm_stages import review_code
        review = review_code(files_content, summary)

        (run_dir / "REVIEW.json").write_text(json.dumps(review, indent=2, default=str), encoding="utf-8")
        result["artifact"] = "REVIEW.json"
        result["review_mode"] = "llm"
        result["review_approved"] = review.get("approved", True)

        if not review.get("approved", True):
            critical_issues = [i for i in review.get("issues", []) if i.get("severity") == "critical"]
            if critical_issues:
                result["warning"] = f"Code review found {len(critical_issues)} critical issues: {review.get('summary', '')}"
                self._raise_if_strict(result)

    def _handle_test_verification(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """Run tests on generated code, falling back to project tests."""
        workspace = self._get_delivery_workspace(context)

        if workspace:
            # Run code sandbox validation on the delivery workspace
            from services.executor.code_sandbox import CodeSandbox
            sandbox = CodeSandbox(workspace)
            sandbox_result = sandbox.validate()
            (run_dir / "TEST.json").write_text(json.dumps(sandbox_result, indent=2), encoding="utf-8")
            result["artifact"] = "TEST.json"
            result["test_mode"] = "sandbox"
            if not sandbox_result.get("passed", True):
                result["warning"] = f"Generated code validation failed: {sandbox_result.get('errors', [])}"
                self._raise_if_strict(result)
            return

        # No delivery workspace — no generated code to test.
        # Skip fallback smoke tests (they require the full project test environment).
        logger.info("No delivery workspace for test-verification; skipping sandbox validation")
        result["artifact"] = "TEST.json"
        result["test_mode"] = "no_delivery_workspace"
        fallback_result = {"passed": True, "details": "No delivery workspace; test verification skipped"}
        (run_dir / "TEST.json").write_text(json.dumps(fallback_result, indent=2), encoding="utf-8")

    def _handle_security_check(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """LLM-powered security analysis of generated code, with tool fallback."""
        files_content = self._collect_delivery_code(context)
        summary = context.get("summary", "")
        workspace = self._get_delivery_workspace(context)

        # First, try running static analysis tools on the generated code
        tool_result = None
        if workspace:
            security_candidates = [
                ["bandit", "-q", "-r", str(workspace)],
                ["ruff", "check", "--select", "S", str(workspace)],
            ]
            for cmd in security_candidates:
                if not self.git_ops.command_exists(cmd[0]):
                    continue
                candidate = self.git_ops.run_command(cmd)
                stderr_lower = (candidate.get("stderr_tail") or "").lower()
                if candidate["returncode"] == 127 or "no module named" in stderr_lower:
                    continue
                tool_result = candidate
                break

        # Then run LLM security analysis
        if files_content != "No delivery workspace available":
            from services.executor.llm_stages import security_analysis
            llm_result = security_analysis(files_content, summary)
        else:
            llm_result = {"safe": True, "vulnerabilities": [], "summary": "No code to analyze"}

        combined = {
            "tool_scan": tool_result,
            "llm_analysis": llm_result,
            "security_mode": "combined" if tool_result else "llm_only",
        }
        (run_dir / "SECURITY.json").write_text(json.dumps(combined, indent=2, default=str), encoding="utf-8")
        result["artifact"] = "SECURITY.json"
        result["security_mode"] = combined["security_mode"]

        # Flag warnings from either source
        warnings = []
        if tool_result and tool_result.get("returncode", 0) not in (0, 127):
            # 127 = command not found — not a security issue
            warnings.append(f"Tool scan: {tool_result.get('stderr_tail', 'failed')}")
        if not llm_result.get("safe", True):
            critical_vulns = [v for v in llm_result.get("vulnerabilities", []) if v.get("severity") in ("critical", "high")]
            if critical_vulns:
                warnings.append(f"LLM found {len(critical_vulns)} critical/high vulnerabilities")
        if warnings:
            result["warning"] = "; ".join(warnings)
            self._raise_if_strict(result)

    def _handle_e2e(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """E2E verification: validate generated code compiles and tests pass."""
        workspace = self._get_delivery_workspace(context)

        if workspace:
            from services.executor.code_sandbox import CodeSandbox
            sandbox = CodeSandbox(workspace)
            sandbox_result = sandbox.validate()
            (run_dir / "E2E.json").write_text(json.dumps(sandbox_result, indent=2), encoding="utf-8")
            result["artifact"] = "E2E.json"
            result["e2e_mode"] = "sandbox"
            if not sandbox_result.get("passed", True):
                result["warning"] = f"E2E validation failed: {sandbox_result.get('errors', [])}"
                self._raise_if_strict(result)
            return

        self._run_command_gate(
            command=[_PYTHON_BIN, "-m", "pytest", "-q", "tests/test_e2e_simulation.py"],
            run_dir=run_dir,
            artifact_name="E2E.json",
            failure_label="E2E verification failed",
            result=result,
        )
        result["e2e_mode"] = "fallback_simulation"

    def _handle_ui_a11y(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """LLM-powered accessibility review of generated UI code."""
        files_content = self._collect_delivery_code(context)
        summary = context.get("summary", "")

        if files_content != "No delivery workspace available":
            from services.executor.llm_stages import accessibility_review
            a11y_result = accessibility_review(files_content, summary)
        else:
            a11y_result = {"compliant": True, "issues": [], "summary": "No UI code to analyze"}

        (run_dir / "UI_A11Y.json").write_text(json.dumps(a11y_result, indent=2, default=str), encoding="utf-8")
        result["artifact"] = "UI_A11Y.json"
        result["a11y_mode"] = "llm" if files_content != "No delivery workspace available" else "skip"

        if not a11y_result.get("compliant", True):
            critical_issues = [i for i in a11y_result.get("issues", []) if i.get("severity") == "critical"]
            if critical_issues:
                result["warning"] = f"Accessibility issues: {a11y_result.get('summary', '')}"
                self._raise_if_strict(result)

    def _handle_documentation(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        """LLM-powered documentation generation."""
        files_content = self._collect_delivery_code(context)

        if files_content != "No delivery workspace available":
            from services.executor.llm_stages import generate_documentation
            doc = generate_documentation(files_content, context)
        else:
            doc = (
                f"# SwarmForge Execution Report\n\n"
                f"- task: {task_id}\n"
                f"- summary: {context.get('summary', '')}\n"
                f"- completed_at: {datetime.now(UTC).isoformat()}\n"
            )

        (run_dir / "REPORT.md").write_text(doc, encoding="utf-8")
        result["artifact"] = "REPORT.md"
        result["doc_mode"] = "llm" if files_content != "No delivery workspace available" else "template"

    def _handle_slo_gate(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        self._run_command_gate(
            command=[_PYTHON_BIN, "-m", "pytest", "-q", "tests/test_sla_monitor.py"],
            run_dir=run_dir,
            artifact_name="SLO_GATE.json",
            failure_label="Post-deploy SLO gate failed",
            result=result,
        )

    def _handle_release_gate(self, run_dir: Path, task_id: str, context: dict[str, Any], result: Dict[str, Any]) -> None:
        diff_stat = self.git_ops.run_command(["git", "diff", "--stat"])
        (run_dir / "RELEASE_GATE.json").write_text(json.dumps(diff_stat, indent=2), encoding="utf-8")
        result["artifact"] = "RELEASE_GATE.json"
        result["command"] = diff_stat["command"]
